version = 1

[[annotations]]
path = [
 ".formatter.exs",
 ".github/CODEOWNERS",
 ".gitignore",
 "CHANGELOG.md",
 "busybox_defconfig",
 "nerves_defconfig",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock",
 "VERSION"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2025 Lars Wikman"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
 "examples/resilience_testing/README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Evercam"
SPDX-License-Identifier = "CC-BY-4.0"

# Buildroot derived or related files
# NOTE: packages here proactively have copyright assigned to the Buildroot
# developers to avoid worrying up copyright assignment when upstreaming.
[[annotations]]
path = [
 "Config.in",
 "package/**",
 "external.mk",
 "post-build.sh",
 "post-createfs.sh"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "The Buildroot developers <buildroot@buildroot.org>"
SPDX-License-Identifier = "GPL-2.0-or-later"

# Linux kernel derived or related files
[[annotations]]
path = [
 "linux/*",
 "linux-6.12.defconfig",
 "ramoops.dts"
]
precedence = "override"
SPDX-FileCopyrightText = "Various"
SPDX-License-Identifier = "GPL-2.0-only"

# Fwup config files
[[annotations]]
path = [
 "fwup-ops.conf",
 "fwup.conf",
 "fwup_include/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Various config files
[[annotations]]
path = [
 "rootfs_overlay/etc/boardid.config",
 "rootfs_overlay/etc/erlinit.config",
 "rootfs_overlay/etc/fw_env.config",
 "rootfs_overlay/etc/sysctl.conf"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# Example app source code and scripts
[[annotations]]
path = [
 "examples/resilience_testing/bin/**",
 "examples/resilience_testing/lib/**",
 "examples/resilience_testing/test/**"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 Evercam"
SPDX-License-Identifier = "Apache-2.0"

# Example app config and boilerplate files
[[annotations]]
path = [
 "examples/resilience_testing/.formatter.exs",
 "examples/resilience_testing/.gitignore",
 "examples/resilience_testing/config/**",
 "examples/resilience_testing/mix.exs",
 "examples/resilience_testing/mix.lock",
 "examples/resilience_testing/rel/vm.args.eex",
 "examples/resilience_testing/rootfs_overlay/etc/iex.exs"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

